[package]
name = "hacklib"
version = "0.0.1"
authors = ["Markus Heikkinen <ittevien@gmail.com>"]

[dependencies]
#winapi = "0.1.17"
#kernel32-sys = "*"

[dependencies.winapi]
path = "winapi-rs"

[dependencies.kernel32-sys]
path = "winapi-rs/lib/kernel32-sys"
