[package]
authors = ["Markus Heikkinen <ittevien@gmail.com>"]
name = "whack"
version = "0.1.0"

[dependencies]
byteorder = "0.5"
lde = "0.1.1"
libc = "0.2"
kernel32-sys = "0.2.1"
rust_win32error = "0.8"
scopeguard = "0.1"
smallvec = "0.1"
winapi = "0.2.5"
