[package]
authors = ["Markus Heikkinen <ittevien@gmail.com>"]
name = "whack"
version = "0.2.0"

[dependencies]
byteorder = "1.1"
lde = "0.2.0"
libc = "0.2"
kernel32-sys = "0.2.1"
rust_win32error = "0.8"
scopeguard = "0.3"
smallvec = "0.6"
winapi = "0.2.5"
