[package]
authors = ["Markus Heikkinen <ittevien@gmail.com>"]
name = "whack"
version = "0.2.0"

[dependencies]
byteorder = "1.1"
lde = "0.2.0"
libc = "0.2"
rust_win32error = "0.8"
scopeguard = "0.3"
smallvec = "0.6"

[dependencies.winapi]
version = "0.3.2"
features = [
    "fileapi", "handleapi", "heapapi", "libloaderapi", "memoryapi", "processenv",
    "tlhelp32", "winerror", "winbase"
]

[dev-dependencies.winapi]
version = "0.3.2"
features = [
    "fileapi", "handleapi", "heapapi", "libloaderapi", "memoryapi", "processenv",
    "sysinfoapi", "tlhelp32", "winerror", "winbase"
]
